-- MySQL Script generated by MySQL Workbench
-- 03/07/17 12:13:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_madera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_madera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_madera` DEFAULT CHARACTER SET utf8 ;
USE `db_madera` ;

-- -----------------------------------------------------
-- Table `db_madera`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`ville` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `code_postal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`commercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`commercial` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `numero_rue` VARCHAR(10) NULL,
  `nom_rue` VARCHAR(100) NULL,
  `portable` VARCHAR(15) NULL,
  `fixe` VARCHAR(15) NULL,
  `email` VARCHAR(60) NULL,
  `login` VARCHAR(60) NULL,
  `mot_passe` VARCHAR(64) NULL,
  `ville_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ville_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_commercial_ville1_idx` (`ville_id` ASC),
  CONSTRAINT `fk_commercial_ville1`
    FOREIGN KEY (`ville_id`)
    REFERENCES `db_madera`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`client` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `numero_rue` VARCHAR(10) NULL,
  `nom_rue` VARCHAR(100) NULL,
  `portable` VARCHAR(15) NULL,
  `fixe` VARCHAR(15) NULL,
  `email` VARCHAR(60) NULL,
  `date_creation` DATE NULL,
  `commercial_id` INT NOT NULL,
  `ville_id` INT NOT NULL,
  PRIMARY KEY (`id`, `commercial_id`, `ville_id`),
  INDEX `fk_client_commercial1_idx` (`commercial_id` ASC),
  INDEX `fk_client_ville1_idx` (`ville_id` ASC),
  CONSTRAINT `fk_client_commercial1`
    FOREIGN KEY (`commercial_id`)
    REFERENCES `db_madera`.`commercial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_ville1`
    FOREIGN KEY (`ville_id`)
    REFERENCES `db_madera`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`projet` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `date_creation` DATE NULL,
  `commercial_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `commercial_id`, `client_id`),
  INDEX `fk_projet_commercial_idx` (`commercial_id` ASC),
  INDEX `fk_projet_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_projet_commercial`
    FOREIGN KEY (`commercial_id`)
    REFERENCES `db_madera`.`commercial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_madera`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`devis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`devis` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `etat` VARCHAR(30) NULL,
  `total_ht` DOUBLE NULL,
  `tva` DOUBLE NULL,
  `remise` DOUBLE NULL,
  `date_creation` DATE NULL,
  `echelonnement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `echelonnement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`coupe_principe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`coupe_principe` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`modele` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `date_creation` DATE NULL,
  `coupe_principe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `coupe_principe_id`),
  INDEX `fk_modele_coupe_principe1_idx` (`coupe_principe_id` ASC),
  CONSTRAINT `fk_modele_coupe_principe1`
    FOREIGN KEY (`coupe_principe_id`)
    REFERENCES `db_madera`.`coupe_principe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`plan` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `date_creation` DATE NULL,
  `projet_id` INT NOT NULL,
  `modele_id` INT NOT NULL,
  PRIMARY KEY (`id`, `projet_id`, `modele_id`),
  INDEX `fk_plan_projet1_idx` (`projet_id` ASC),
  INDEX `fk_plan_modele1_idx` (`modele_id` ASC),
  CONSTRAINT `fk_plan_projet1`
    FOREIGN KEY (`projet_id`)
    REFERENCES `db_madera`.`projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_modele1`
    FOREIGN KEY (`modele_id`)
    REFERENCES `db_madera`.`modele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`gamme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`gamme` (
  `id` INT NOT NULL,
  `finition_exterieure` VARCHAR(30) NULL,
  `isolant` VARCHAR(30) NULL,
  `couverture` VARCHAR(30) NULL,
  `type_angle` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`module` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `longueur` DOUBLE NULL,
  `prix_ht` DOUBLE NULL,
  `gamme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gamme_id`),
  INDEX `fk_module_gamme1_idx` (`gamme_id` ASC),
  CONSTRAINT `fk_module_gamme1`
    FOREIGN KEY (`gamme_id`)
    REFERENCES `db_madera`.`gamme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`composant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`composant` (
  `id` INT NOT NULL,
  `nature` VARCHAR(45) NULL,
  `caracteristiques` VARCHAR(70) NULL,
  `unite_usage` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`Famille_composant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`Famille_composant` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`CCTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`CCTP` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`echelonnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`echelonnement` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  `taux` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_madera`.`echelonnement_devis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_madera`.`echelonnement_devis` (
  `echelonnement_id` INT NOT NULL,
  `devis_id` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`echelonnement_id`, `devis_id`),
  INDEX `fk_echelonnement_has_devis_devis1_idx` (`devis_id` ASC),
  INDEX `fk_echelonnement_has_devis_echelonnement1_idx` (`echelonnement_id` ASC),
  CONSTRAINT `fk_echelonnement_has_devis_echelonnement1`
    FOREIGN KEY (`echelonnement_id`)
    REFERENCES `db_madera`.`echelonnement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_echelonnement_has_devis_devis1`
    FOREIGN KEY (`devis_id`)
    REFERENCES `db_madera`.`devis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
